routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\SubKriteriaController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\PerhitunganController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/login', function () {
//     return view('login');
// });

Route::get('/', [AuthController::class, 'showFormLogin'])->name('login');
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);

Route::group(['middleware' => 'auth'], function () {
    
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('subkriteria', SubKriteriaController::class);
    Route::resource('mahasiswa', MahasiswaController::class);
    Route::resource('perhitungan', PerhitunganController::class);
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
 
});

app/Models/Mahasiswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mahasiswa extends Model
{
    use HasFactory;
}

app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Subkriteria;
use App\Models\Kriteria;
use App\Models\Mahasiswa;
use App\Models\Nilai;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class MahasiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $listMahasiswa = Mahasiswa::all();
        return view('mahasiswa.index',compact('listMahasiswa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $listSubKriteria = Subkriteria::all()->sortBy('kode_subkriteria');
        return view('mahasiswa.create',compact('listSubKriteria'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $nilai = $request->input('nilai');
        $kode = $request->input('kode_subkriteria');

        $value = [];
        $i= 0;
        foreach ($nilai as $data) {
            array_push($value, array(
                'nim' => $request->input('nim'),
                'nilai' => $data,
                'kode_subkriteria' => $kode[$i]
            ));
            $i++;
        }
        $current_time = \Carbon\Carbon::now()->toDateTimeString();

        $mahasiswa = array(
            'nim' => $request->input('nim'),
            'nama' => $request->input('nama_mahasiswa'),
            'user_id' => Auth::user()->id,
            'tanggal' => $current_time
        );
        DB::table('nilais')->insert($value);
        DB::table('mahasiswas')->insert($mahasiswa);

        return redirect()->route('mahasiswa.index')
                        ->with('success','tambah data mahasiswa berhasil');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($nim)
    {
        $data = Mahasiswa::firstOrFail()->where('nim',$nim)->get();
        $mahasiswa = $data[0];
        $nilai = DB::table('nilais')
        ->select('nilais.nim','nilais.nilai',  
            DB::raw("(select subkriterias.nama_subkriteria from subkriterias 
                    where subkriterias.kode_subkriteria = nilais.kode_subkriteria) as nama_subkriteria"))
        ->orderBy('nilais.kode_subkriteria')
        ->where('nilais.nim', $nim)
        ->get();
        return view('mahasiswa.show',compact('mahasiswa', 'nilai', 'nim'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($nim)
    {
        $data = Mahasiswa::firstOrFail()->where('nim',$nim)->get();
        $mahasiswa = $data[0];
        $nilai = DB::table('nilais')
        ->select('nilais.nim','nilais.nilai', 'nilais.kode_subkriteria', 
            DB::raw("(select subkriterias.nama_subkriteria from subkriterias 
                    where subkriterias.kode_subkriteria = nilais.kode_subkriteria) as nama_subkriteria"))
        ->orderBy('nilais.kode_subkriteria')
        ->where('nilais.nim', $nim)
        ->get();
        $listSubKriteria = Subkriteria::all();
        return view('mahasiswa.edit',compact('mahasiswa', 'nilai'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $nim)
    {
        $nilai = $request->input('nilai');
        $kode = $request->input('kode_subkriteria');

        $value = [];
        $i= 0;
        foreach ($nilai as $data) {
            DB::table('nilais')->where('nim', $nim)->where('kode_subkriteria', $kode[$i])->update(array(
                'nim' => $request->input('nim'),
                'nilai' => $data));
            $i++;
        }

        $current_time = \Carbon\Carbon::now()->toDateTimeString();

        $mahasiswa = array(
            'nim' => $request->input('nim'),
            'nama' => $request->input('nama_mahasiswa'),
            'user_id' => Auth::user()->id,
            'tanggal' => $current_time
        );
        DB::table('mahasiswas')->where('nim', $nim)->update($mahasiswa);

        return redirect()->route('mahasiswa.index')
                        ->with('success','edit data mahasiswa berhasil');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($nim)
    {
        Mahasiswa::firstOrFail()->where('nim',$nim)->delete();
        Nilai::firstOrFail()->where('nim',$nim)->delete();
        return redirect()->route('mahasiswa.index')
                        ->with('success','hapus data mahasiswa berhasil');
    }

}

resources/views/mahasiswa/create.blade.php
@extends('template')
 
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Input Nilai Mahasiswa</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('mahasiswa.index') }}"> Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('mahasiswa.store') }}" method="POST">
    @csrf
 
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nim :</strong>
                <input type="text" name="nim" class="form-control" placeholder="Nim" required>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Mahasiswa:</strong>
                <input type="text" name="nama_mahasiswa" class="form-control" placeholder="Nama Mahasiswa" required>
            </div>
        </div>
        @foreach ($listSubKriteria as $subkriteria)
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>{{ $subkriteria->nama_subkriteria }}:</strong>
                <input type="text" name="nilai[]" class="form-control" placeholder="Nilai" required>
                <input type="text" name="kode_subkriteria[]" value="{{ $subkriteria->kode_subkriteria }}" hidden>
            </div>
        </div>
        @endforeach
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
 
</form>
@endsection

resources/views/mahasiswa/edit.blade.php
@extends('template')
 
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Edit Data Mahasiswa</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('mahasiswa.index') }}"> Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('mahasiswa.update',$mahasiswa->nim) }}" method="POST">
    @csrf
    @method('PUT')
    
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nim :</strong>
                <input type="text" name="nim" class="form-control" placeholder="Nim" value="{{$mahasiswa->nim}}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Mahasiswa:</strong>
                <input type="text" name="nama_mahasiswa" class="form-control" placeholder="Nama Mahasiswa" value="{{$mahasiswa->nama}}">
            </div>
        </div>
        @foreach ($nilai as $n)
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>{{ $n->nama_subkriteria }}:</strong>
                <input type="text" name="nilai[]" class="form-control" placeholder="Nilai" value="{{$n->nilai}}">
                <input type="text" name="kode_subkriteria[]" value="{{ $n->kode_subkriteria }}" hidden>
            </div>
        </div>
        @endforeach
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
 
</form>
@endsection

resources/views/mahasiswa/index.blade.php
@extends('template')
 
@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Mahasiswa</h2>
            </div>
            @if(!Auth::user()->role == 'akademik')
            <div class="float-right">
                <a class="btn btn-success" href="{{ route('mahasiswa.create') }}">Tambah Data</a>
            </div>
            @endif
        </div>
    </div>
 
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif

    
    <table class="table table-bordered">
        <tr>
            <th width="20px" class="text-center">Nim</th>
            <th width="50px" class="text-center">Nama Mahasiswa</th>
            <th width="280px"class="text-center">Action</th>
        </tr>
        @foreach ($listMahasiswa as $mahasiswa)
        <tr>
                <td width="20px" class="text-center">{{$mahasiswa->nim}}</td>
                <td width="50px" class="text-center">{{$mahasiswa->nama}}</td>
                <td class="text-center">
                    <form action="{{ route('mahasiswa.destroy',$mahasiswa->nim) }}" method="POST">
    
                        <a class="btn btn-primary btn-sm" href="{{ route('mahasiswa.show',$mahasiswa->nim) }}">Lihat Nilai</a>
                        @if(!Auth::user()->role == 'akademik')
                            <a class="btn btn-success btn-sm" href="{{ route('mahasiswa.edit',$mahasiswa->nim) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                        @endif
                    </form>
                </td>
        </tr>
        @endforeach
    </table>

    <a class="btn btn-success" href="{{ route('perhitungan.index') }}">Perhitungan Data</a>
@endsection

resources/views/mahasiswa/show.blade.php
@extends('template')
 
@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Nama : {{$mahasiswa->nama}}</h2>
                <h2>Nim : {{$mahasiswa->nim}}</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-success" href="{{ route('mahasiswa.edit',$nim) }}">Edit Data</a>
            </div>
        </div>
    </div>
 
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif

    
    <table class="table table-bordered">
        <tr>
            <th>Nama SubKriteria</th>
            <th>Nilai</th>
        </tr>
        @foreach ($nilai as $n)
        <tr>
            <td>{{$n->nama_subkriteria}}</td>
            <td>{{$n->nilai}}</td>
        </tr>
        @endforeach
    </table>


@endsection