routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\SubKriteriaController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\PerhitunganController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/login', function () {
//     return view('login');
// });

Route::get('/', [AuthController::class, 'showFormLogin'])->name('login');
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);

Route::group(['middleware' => 'auth'], function () {
    
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('subkriteria', SubKriteriaController::class);
    Route::resource('mahasiswa', MahasiswaController::class);
    Route::resource('perhitungan', PerhitunganController::class);
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
 
});

app/Models/Subkriteria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Subkriteria extends Model
{
    use HasFactory;

    protected $fillable = [
        'kode_subkriteria', 'nama_subkriteria', 'tipe', 'kode_kriteria', 'bobot'
    ];
}

app/Http/Controllers/SubKriteriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Subkriteria;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;

class SubKriteriaController extends Controller
{
    public function index()
    {
        /// mengambil data terakhir dan pagination 5 list
        $listSubKriteria = Subkriteria::all()->sortBy('kode_subkriteria');
        /// mengirimkan variabel $kriteria ke halaman views kriteria/index.blade.php
        /// include dengan number index
        return view('subkriteria.index',compact('listSubKriteria'));
            // ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('subkriteria.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /// membuat validasi untuk title dan content wajib diisi
        $request->validate([
            'kode_subkriteria' => 'required',
            'nama_subkriteria' => 'required',
            'kode_kriteria' => 'required',
        ]);
        echo $request;
        /// insert setiap request dari form ke dalam database via model
        /// jika menggunakan metode ini, maka nama field dan nama form harus sama
        Subkriteria::create($request->all());
         
        /// redirect jika sukses menyimpan data
        return redirect()->route('subkriteria.index')
                        ->with('success','Kriteria created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /// dengan menggunakan resource, kita bisa memanfaatkan model sebagai parameter
        /// berdasarkan id yang dipilih
        /// href="{{ route('SubKriterias.show',$SubKriteria->id) }}
        return view('subkriteria.show',compact('kriteria'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($kode_subkriteria)
    {
        $data = Subkriteria::firstOrFail()->where('kode_subkriteria',$kode_subkriteria)->get();
        $subkriteria = $data[0];
        return view('subkriteria.edit',compact('subkriteria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $kode_subkriteria)
    {
        /// membuat validasi untuk title dan content wajib diisi
        $request->validate([
            'kode_subkriteria' => 'required',
            'nama_subkriteria' => 'required',
            'tipe' => 'required',
            'kode_kriteria' => 'required',
        ]);

        /// mengubah data berdasarkan request dan parameter yang dikirimkan
        DB::table('subkriterias')->where('kode_subkriteria',$kode_subkriteria)->update($request->except(['_token','_method']));
         
        /// setelah berhasil mengubah data
        return redirect()->route('subkriteria.index')
                        ->with('success','SubKriteria updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($kode_subkriteria)
    {
        /// melakukan hapus data berdasarkan parameter yang dikirimkan
        Subkriteria::firstOrFail()->where('kode_subkriteria',$kode_subkriteria)->delete();
        return redirect()->route('subkriteria.index')
                        ->with('success','SubKriteria deleted successfully');
    }
}

resources/views/subkriteria/create.blade.php
@extends('template')
 
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create New SubKriteria</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('kriteria.index') }}"> Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('subkriteria.store') }}" method="POST">
    @csrf
 
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kode SubKriteria:</strong>
                <input type="text" name="kode_subkriteria" class="form-control" placeholder="Kode SubKriteria">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama SubKriteria:</strong>
                <input type="text" name="nama_subkriteria" class="form-control" placeholder="Nama SubKriteria">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tipe:</strong><br>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipe" id="flexRadioDefault1" value="Core Factor">
                    <label class="form-check-label" for="flexRadioDefault1">
                        Core Factor
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipe" id="flexRadioDefault2" value="Secondary Factor">
                    <label class="form-check-label" for="flexRadioDefault2">
                        Secondary Factor
                    </label>
                </div>          
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Bobot Kriteria:</strong>
                <input type="text" name="bobot" class="form-control" placeholder="Bobot Kriteria">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kode Kriteria:</strong>
                <input type="text" name="kode_kriteria" class="form-control" placeholder="Kode Kriteria">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
 
</form>
@endsection

resources/views/subkriteria/edit.blade.php
@extends('template')
 
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Edit SubKriteria</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('subkriteria.index') }}"> Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('subkriteria.update', $subkriteria->kode_subkriteria) }}" method="POST">
    @csrf
    @method('PUT')
 
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kode SubKriteria:</strong>
                <input type="text" name="kode_subkriteria" class="form-control" placeholder="Kode SubKriteria" value="{{ $subkriteria->kode_subkriteria }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama SubKriteria:</strong>
                <input type="text" name="nama_subkriteria" class="form-control" placeholder="Nama SubKriteria" value="{{ $subkriteria->nama_subkriteria }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
            <strong>Tipe:</strong><br>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipe" id="flexRadioDefault1" value="Core Factor" 
                        {{$subkriteria->tipe = 'Core Factor' ? 'checked' : ''}} >
                    <label class="form-check-label" for="flexRadioDefault1">
                        Core Factor
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipe" id="flexRadioDefault2" value="Secondary Factor"
                    {{$subkriteria->tipe = 'Secondary Factor' ? 'checked' : ''}} >
                    <label class="form-check-label" for="flexRadioDefault2">
                        Secondary Factor
                    </label>
                </div>      
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Bobot Kriteria:</strong>
                <input type="text" name="bobot" class="form-control" placeholder="Bobot Kriteria" value="{{ $subkriteria->bobot }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kode Kriteria:</strong>
                <input type="text" name="kode_kriteria" class="form-control" placeholder="Kode SubKriteria" value="{{ $subkriteria->kode_kriteria }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
 
</form>
@endsection

resources/views/subkriteria/index.blade.php
@extends('template')
 
@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>SubKriteria</h2>
            </div>
            @if(Auth::user()->role == 'admin')
            <div class="float-right">
                <a class="btn btn-success" href="{{ route('subkriteria.create') }}"> Create SubKriteria</a>
            </div>
            @endif
        </div>
    </div>
 
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
 
    <table class="table table-bordered">
        <tr>
            <th width="20px" class="text-center">Kode SubKriteria</th>
            <th width="50px" class="text-center">Nama SubKriteria</th>
            <th width="50px" class="text-center">Tipe</th>
            <th width="50px" class="text-center">Bobot</th>
            <th width="50px" class="text-center">Kode Kriteria</th>
            @if(Auth::user()->role == 'admin')
            <th width="280px"class="text-center">Action</th>
            @endif
        </tr>
        @foreach ($listSubKriteria as $subkriteria)
        <tr>
            <td>{{ $subkriteria->kode_subkriteria }}</td>
            <td>{{ $subkriteria->nama_subkriteria }}</td>
            <td>{{ $subkriteria->tipe }}</td>
            <td>{{ $subkriteria->bobot }}</td>
            <td>{{ $subkriteria->kode_kriteria }}</td>
            @if(Auth::user()->role == 'admin')
            <td class="text-center">
                <form action="{{ route('subkriteria.destroy',$subkriteria->kode_subkriteria) }}" method="POST">
  
                    <a class="btn btn-primary btn-sm" href="{{ route('subkriteria.edit',$subkriteria->kode_subkriteria) }}">Edit</a>
 
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                </form>
            </td>
            @endif
        </tr>
        @endforeach
    </table>
 
 
@endsection