routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\SubKriteriaController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\PerhitunganController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/login', function () {
//     return view('login');
// });

Route::get('/', [AuthController::class, 'showFormLogin'])->name('login');
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);

Route::group(['middleware' => 'auth'], function () {
    
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('subkriteria', SubKriteriaController::class);
    Route::resource('mahasiswa', MahasiswaController::class);
    Route::resource('perhitungan', PerhitunganController::class);
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
 
});

app/Models/Kriteria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kriteria extends Model
{
    use HasFactory;

    protected $fillable = [
        'kode_kriteria', 'nama_kriteria', 'persentase_kriteria', 'persentase_core' ,'persentase_second'
    ];
}

app/Http/Controllers/KriteriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kriteria;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;

class KriteriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /// mengambil data kriteria
        $listKriteria = Kriteria::all();

        /// mengirimkan variabel $kriteria ke halaman views kriteria/index.blade.php
        /// include dengan number index
        return view('kriteria.index',compact('listKriteria'));
            // ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kriteria.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /// membuat validasi untuk title dan content wajib diisi
        $request->validate([
            'kode_kriteria' => 'required',
            'nama_kriteria' => 'required',
            'persentase_kriteria' => 'required',
            'persentase_core' => 'required',
            'persentase_second' => 'required'
        ]);
        /// insert setiap request dari form ke dalam database via model
        /// jika menggunakan metode ini, maka nama field dan nama form harus sama
        Kriteria::create($request->all());
         
        /// redirect jika sukses menyimpan data
        return redirect()->route('kriteria.index')
                        ->with('success','Kriteria created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /// dengan menggunakan resource, kita bisa memanfaatkan model sebagai parameter
        /// berdasarkan id yang dipilih
        /// href="{{ route('posts.show',$post->id) }}
        return view('kriteria.show',compact('kriteria'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($kode_kriteria)
    {
        $data = Kriteria::firstOrFail()->where('kode_kriteria',$kode_kriteria)->get();
        $kriteria = $data[0];
        return view('kriteria.edit',compact('kriteria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $kode_kriteria)
    {
        $request->validate([
            'kode_kriteria' => 'required',
            'nama_kriteria' => 'required',
            'persentase_kriteria' => 'required',
            'persentase_core' => 'required',
            'persentase_second' => 'required'
        ]);

        /// mengubah data berdasarkan request dan parameter yang dikirimkan
        DB::table('kriterias')->where('kode_kriteria',$kode_kriteria)->update($request->except(['_token','_method']));
         
        /// setelah berhasil mengubah data
        return redirect()->route('kriteria.index')
                        ->with('success','Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($kode_kriteria)
    {
        /// melakukan hapus data berdasarkan parameter yang dikirimkan
        Kriteria::firstOrFail()->where('kode_kriteria',$kode_kriteria)->delete();
        return redirect()->route('kriteria.index')
                        ->with('success','Post deleted successfully');
    }
}

resources/views/kriteria/create.blade.php
@extends('template')
 
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create New Kriteria</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('kriteria.index') }}"> Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('kriteria.store') }}" method="POST">
    @csrf
 
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kode Kriteria:</strong>
                <input type="text" name="kode_kriteria" class="form-control" placeholder="Kode Kriteria">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Kriteria:</strong>
                <input type="text" name="nama_kriteria" class="form-control" placeholder="Nama Kriteria">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>persentase kriteria:</strong>
                <input type="text" name="persentase_kriteria" class="form-control" placeholder="presentase Kriteria">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>persentase core</strong>
                <input type="text" name="persentase_core" class="form-control" placeholder="persentase core">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>persentase second:</strong>
                <input type="text" name="persentase_second" class="form-control" placeholder="persentase second">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
 
</form>
@endsection

resources/views/kriteria/edit.blade.php
@extends('template')
 
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create New Kriteria</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('kriteria.index') }}"> Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('kriteria.update', $kriteria->kode_kriteria) }}" method="POST">
    @csrf
    @method('PUT')
 
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kode Kriteria:</strong>
                <input type="text" name="kode_kriteria" class="form-control" placeholder="Kode Kriteria" value="{{ $kriteria->kode_kriteria }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Kriteria:</strong>
                <input type="text" name="nama_kriteria" class="form-control" placeholder="Nama Kriteria" value="{{ $kriteria->nama_kriteria }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>persentase kriteria:</strong>
                <input type="text" name="persentase_kriteria" class="form-control" placeholder="presentase Kriteria" value="{{ $kriteria->persentase_kriteria }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>persentase core</strong>
                <input type="text" name="persentase_core" class="form-control" placeholder="persentase core" value="{{ $kriteria->persentase_core }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>persentase second:</strong>
                <input type="text" name="persentase_second" class="form-control" placeholder="persentase second" value="{{ $kriteria->persentase_second }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
 
</form>
@endsection

resources/views/kriteria/index.blade.php
@extends('template')
 
@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Kriteria</h2>
            </div>
            @if(Auth::user()->role == 'admin')
            <div class="float-right">
                <a class="btn btn-success" href="{{ route('kriteria.create') }}"> Create Post</a>
            </div>
            @endif
        </div>
    </div>
 
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
 
    <table class="table table-bordered">
        <tr>
            <th width="20px" class="text-center">Kode Kriteria</th>
            <th width="50px" class="text-center">Nama Kriteria</th>
            <th width="50px" class="text-center">persentase kriteria</th>
            <th width="50px" class="text-center">persentase core</th>
            <th width="50px" class="text-center">persentase second</th>
            @if(Auth::user()->role == 'admin')
            <th width="280px"class="text-center">Action</th>
            @endif
        </tr>
        @foreach ($listKriteria as $kriteria)
        <tr>
            <td>{{ $kriteria->kode_kriteria }}</td>
            <td>{{ $kriteria->nama_kriteria }}</td>
            <td>{{ $kriteria->persentase_kriteria }}</td>
            <td>{{ $kriteria->persentase_core }}</td>
            <td>{{ $kriteria->persentase_second }}</td>
            @if(Auth::user()->role == 'admin')
            <td class="text-center">
                <form action="{{ route('kriteria.destroy',$kriteria->kode_kriteria) }}" method="POST">
 
                    <!-- <a class="btn btn-info btn-sm" href="{{ route('kriteria.show',$kriteria->kode_kriteria) }}">Show</a> -->
 
                    <a class="btn btn-primary btn-sm" href="{{ route('kriteria.edit',$kriteria->kode_kriteria) }}">Edit</a>
 
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                </form>
            </td>
            @endif
        </tr>
        @endforeach
    </table>
 
 
@endsection